### ISSUE TITLE
Practica 9-Diagrama de clases

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo_tec#1]
Equipo integrado por:
*  Daisy Gonzalez Lita
*  Adriana Hernández Martínez 
*  Maribel Santiago Bautista
Diagramas de clases
https://github.com/SistemasTecTlaxiaco/CoffeTec/wiki/4-Diagrama-de-clases

Diagramas de secuencia
https://github.com/SistemasTecTlaxiaco/CoffeTec/wiki/5.-Diagramas-de-Secuencia

REPORTE DE LA PRÁCTICA
[PRACTICA_9.pdf](https://github.com/user-attachments/files/18040903/PRACTICA_9.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
Su trabajo cumple con las espectativas, por lo que han alcanzado un 28% del porcentaje total

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
